spring.application.name=BeSy
server.port=3000

# Locale configuration (can be overridden via LOCALE environment variable)
app.locale=${LOCALE:de_DE}


# Production config
spring.profiles.active=development

# Production config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.properties.hibernate.default_schema=migrated_data

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-only
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql = true
spring.datasource.hikari.auto-commit=false
spring.jpa.properties.hibernate.jdbc.batch_size=1000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

api.prefix=/api/v1

spring.jackson.property-naming-strategy=SNAKE_CASE

# activates Error logging
server.error.include-message=always

# activates security logging
logging.level.org.springframework.security=DEBUG

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html


# ===== Keycloak OAuth2 Login Configuration =====

# OAuth Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.insy.hs-esslingen.com/realms/insy

# OAuth Client
spring.security.oauth2.client.registration.besy-for-insy-client.provider=keycloak-server
spring.security.oauth2.client.registration.besy-for-insy-client.client-id=besy-for-insy-client
spring.security.oauth2.client.registration.besy-for-insy-client.client-secret=1nt80UF7TJ0RBvys0ZF9NdKlsZLLhC21
spring.security.oauth2.client.registration.besy-for-insy-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.besy-for-insy-client.scope=profile
spring.security.oauth2.client.provider.keycloak-server.issuer-uri=https://auth.insy.hs-esslingen.com/realms/insy

# Name of the keycloak client, that is used for accessing this spring boot app's ressources
keycloak-client-id=besy


besy-frontend-url=http://localhost:4200
dekan-role-name=dekan
user-role-name=orderer

# Insy settings
insy.api.base-url=https://api.test.insy.hs-esslingen.com
insy.api.orders-url=/orders
insy.api.orders.password=secret
insy.api.orders.username=besy
insy.api.client.name=besy-for-insy-client
# Authorization can either be "basic" or "oauth2"
insy.api.client.authorization.protocol=oauth2

# =====  Paperless-ngx Configuration =====

# Authentication token for user saliit01
paperless.api.token=8e9c79dfcf92026988d8727c9ae2f447d03f9b71

# API URLs
paperless.api.base-url=http://localhost:8000
paperless.api.upload-url=/api/documents/post_document/
paperless.api.search-url=/api/documents/
paperless.api-task-url=/api/tasks/
paperless.api.autocomplete-url=/api/search/autocomplete/
paperless.api.download-url=/api/documents/{id}/download/
paperless.api.preview-url=/api/documents/{id}/thumb/


retry.maxAttempts=6
retry.maxDelay=5000

order-number.prefix=IT
order-number.separator=/
